### PR TITLE
Add support for drmModeGetFB2

### PR DESCRIPTION
**Pull request by emersion**
This relies on [1].

[1]: https://gitlab.freedesktop.org/mesa/drm/-/commit/d8731e9eec93494cc76e7ec5207d13338305fa98

### CODE REVIEW

**Comment by emersion** [comment]
Hmm. Since this depends on a new libdrm function, we can't use the subproject trick, we'll need to wait for Debian to get a recent enough libdrm. Maybe that's a case where an `#ifdef` is in order?

**Comment by ascent12** [comment]
Yeah, I think an #ifdef is appropriate here.

**Comment by emersion** [comment]
This is now ready for review. Tested with libdrm-git and drm-tip (linux 5.6).

**Comment by progandy** [comment]
Is there a reason the commit message mentions ```drmModeAddFB2``` when the code calls ```drmModeGetFB2```?

**Comment by emersion** [comment]
Good catch, fixed.

**Comment by emersion** [comment]
Linux 5.7 is now in Arch repos and has the new GETFB2 ioctl.

**Comment by ascent12** [comment]
Thanks

**Pull request merged**
